import { Component, NgZone, ViewChild } from '@angular/core';
import { BarcodeScanner, BarcodeScanResult } from '@fttx/barcode-scanner';
import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';
import { TranslateService } from '@ngx-translate/core';
import { AlertController, NavController, Slides, ViewController } from 'ionic-angular';
import { Observable, Subscription } from 'rxjs';
import { Config } from '../../providers/config';
import { ServerProvider } from '../../providers/server';
import { Settings } from '../../providers/settings';
import { Utils } from '../../providers/utils';
import { ScanSessionsPage } from '../scan-sessions/scan-sessions';
import { ServerModel } from './../../models/server.model';
import { debounce } from 'helpful-decorators';
declare var window: any;

/*
  Generated class for the Welcome page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'page-welcome',
  templateUrl: 'welcome.html'
})
export class WelcomePage {
  @ViewChild('slider') slider: Slides;
  public showNext = true;
  public connecting = true;
  public connected = false;

  private troubleshootingDialogTimeout = null;
  public currentAttemptingServer: ServerModel;
  private onConnectSubscription: Subscription;

  constructor(
    private alertCtrl: AlertController,
    public navCtrl: NavController,
    private serverProvider: ServerProvider,
    public viewCtrl: ViewController,
    private settings: Settings,
    private ngZone: NgZone,
    private barcodeScanner: BarcodeScanner,
    private utils: Utils,
    private iab: InAppBrowser,
  ) { }

  ionViewDidEnter() {
    window.cordova.plugins.firebase.analytics.setCurrentScreen("WelcomePage");
    this.onConnectSubscription = this.serverProvider.onConnect().subscribe((server) => {
      this.settings.setDefaultServer(server);
      this.slider.slideTo(this.slider.length() - 1);
      this.ngZone.run(() => {
        this.connecting = false;
        this.showNext = false;
      });
      this.connected = true;
      this.serverProvider.stopWatchForServers();
    });

    window.installReferrer.getReferrer((data: any) => {
      // Attempt to connect using referrer parameter from PlayStore
      // Example url generated by the QR Code:
      //  https://app.barcodetopc.com/?h=REFFERERR&a=192.168.0.9-192.168.0.21
      // Which redirects to:
      //  https://play.google.com/store/apps/details?id=com.barcodetopc&referrer=utm_source%3Dbarcode-to-pc-server%26utm_medium%3Dqr-code-pairing%26a%3D192.168.0.9-192.168.0.21%26h%3DREFFERERR
      if (data && data.a) {
        let addresses = data.a.split('-');
        let hostName = data.h || '';
        Observable.from(addresses)
          .zip(Observable.timer(0, 2000), x => x)
          .subscribe((address: string) => {
            this.attempConnection(ServerModel.AddressToServer(address, hostName), true);
          });
      }
    }, (error) => {
      // console.log('[installReferrer] error');
    });

    // this code is kind of duplicated for the "Try again" button
    this.serverProvider.watchForServers().delay(500).subscribe(data => { // delay to prevent this.slide null when the server gets published too fast
      if (data.action == 'added' || data.action == 'resolved') {
        this.attempConnection(data.server)
      }
    });
  }

  ionViewDidLeave() {
    this.serverProvider.stopWatchForServers();
    this.onConnectSubscription.unsubscribe();
    clearTimeout(this.troubleshootingDialogTimeout);
  }

  async onSkipClicked() {
    window.cordova.plugins.firebase.analytics.logEvent('welcome', {});

    let alert = this.alertCtrl.create({
      inputs: [
        {
          type: 'checkbox',
          label: await this.utils.text('dontShowAnymoreDialogLabel'),
          value: 'alwaysSkipWelcomePage',
          checked: false
        }
      ],
      buttons: [
        {
          text: await this.utils.text('dontShowAnymoreSkipButton'),
          handler: data => {
            if (data == 'alwaysSkipWelcomePage') {
              this.settings.setAlwaysSkipWelcomePage(true);
            }
            this.navCtrl.setRoot(ScanSessionsPage);
          }
        }
      ]
    });
    alert.present();
  }

  onNextClicked() {
    this.slider.slideNext();
  }

  onScanQRCodeClicked() {
    this.barcodeScanner.scan({
      "showFlipCameraButton": true, // iOS and Android
      formats: "QR_CODE"
    }).subscribe((scan: BarcodeScanResult) => {
      if (scan && scan.text) {
        let servers = ServerModel.serversFromJSON(scan.text);
        servers.forEach(server => {
          this.attempConnection(server);
        })
      }
    }, err => { });
  }

  startScanningClicked() {
    window.cordova.plugins.firebase.analytics.logEvent('welcome', {});
    this.navCtrl.setRoot(ScanSessionsPage);
  }

  onSlideChanged() {
    this.showNext = !this.slider.isEnd();
    if (this.slider.isEnd()) {
      this.scheduleShowTroubleshootingDialog();
      if (!this.settings.getSkipWiFiCheck()) this.utils.askWiFiEnableIfDisabled();
    }
  }

  getWebSiteName() {
    return Config.WEBSITE_NAME;
  }

  @debounce(2000)
  attempConnection(server: ServerModel, skipQueue = false) {
    if (this.connecting) {
      this.slider.slideTo(this.slider.length() - 1);
      this.currentAttemptingServer = server;
      this.serverProvider.connect(server, skipQueue)
      this.scheduleShowTroubleshootingDialog();
    }
  }

  scheduleShowTroubleshootingDialog() {
    if (this.troubleshootingDialogTimeout) clearTimeout(this.troubleshootingDialogTimeout);

    this.troubleshootingDialogTimeout = setTimeout(async () => {
      if (this.connecting) {
        let alert = this.alertCtrl.create({
          title: await this.utils.text('connectionTakingTooLongDialogTitle'),
          message: await this.utils.text('connectionTakingTooLongDialogMessage'),
          buttons: [
            {
              text: await this.utils.text('connectionTakingTooLongCancelButton'),
              role: 'cancel',
              handler: () => { }
            },
            {
              text: await this.utils.text('connectionTakingTooLongTryAgainButton'),
              handler: () => {
                // This code is duplicated in ionViewDidEnter
                this.serverProvider.watchForServers().subscribe(data => {
                  if (data.action == 'added' || data.action == 'resolved') {
                    this.attempConnection(data.server)
                  }
                });
              }
            },
            {
              text: await this.utils.text('connectionTakingTooLongViewInstructionsButton'),
              handler: () => {
                this.iab.create(Config.URL_INSTRUCTIONS, '_system');
              }
            }
          ]
        });
        alert.present();
      }
    }, 1000 * 25) // 25 secs
  }
}
